name: Tests
on:
  workflow_call:
jobs:
  hvm-tests:
    name: 🔎 HVM Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        run_mode: [interpreted, compiled, single-thread]
        exclude:
          - os: windows-latest
            run_mode: compiled
          - os: windows-latest
            run_mode: single-thread
    env:
      # Add .exe suffix to HVM command on Windows
      HVM_CMD: ${{matrix.os != 'windows-latest' && './target/release/hvm' || './target/release/hvm.exe'}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - run: cargo build --release
      # FIXME: compiled mode of kind 2 teste don't work because compiled
      # code don't have sugar for strings
      - run: python3 -X utf8 tests/test_cli.py --hvm-cmd ${{env.HVM_CMD}} --run-mode ${{ matrix.run_mode }} --skip-test kind2
